---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull pratyu2364/mavenrep:latest

    - name: running container
      shell: docker run -it -d pratyu2364/mavenrep:latest